/**
 * inject-env.js
 * Netlify build script: bakes SUPABASE_URL and SUPABASE_ANON_KEY
 * into a tiny JS file (js/env.js) so plain HTML pages can read them
 * without a backend or bundler.
 *
 * Runs as: node inject-env.js
 * Called by netlify.toml [build] command.
 */

const fs   = require('fs');
const path = require('path');

const SUPABASE_URL      = process.env.SUPABASE_URL      || 'YOUR_SUPABASE_URL';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || 'YOUR_SUPABASE_ANON_KEY';

// Write a tiny env shim that auth.js reads from window.__ENV__
const content = `// Auto-generated by inject-env.js at build time. Do not edit.
window.__ENV__ = {
  SUPABASE_URL:      ${JSON.stringify(SUPABASE_URL)},
  SUPABASE_ANON_KEY: ${JSON.stringify(SUPABASE_ANON_KEY)}
};
`;

const out = path.join(__dirname, 'js', 'env.js');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, content, 'utf8');

console.log('[CodeCoach] env.js written.');
console.log('  SUPABASE_URL:', SUPABASE_URL !== 'YOUR_SUPABASE_URL' ? '✅ set' : '⚠️  not set');
console.log('  SUPABASE_ANON_KEY:', SUPABASE_ANON_KEY !== 'YOUR_SUPABASE_ANON_KEY' ? '✅ set' : '⚠️  not set');
